Change README.md
SirusCodes/test pull request #3
Opened 2021-02-28 07:03 UTC by sankalpsp07

Changes suggested by @HarshKapadia2

2021-02-28 07:26 UTC, HarshKapadia2 commented
Merge this one, @SirusCodes 😛 😂

2021-02-28 08:31 UTC, SirusCodes requested changes
The changes which you have made is not true and we won't accept spreading false information for our users.

Please make proper changes to the docs.

2021-02-28 10:20 UTC, HarshKapadia2 commented
What has been stated is the truth and nothing but the truth.
It is shameful to see the owner of this repository trying to suppress the truth. 😛

2021-02-28 10:27 UTC, SirusCodes commented
> What has been stated is the truth and nothing but the truth.
> It is shameful to see the owner of this repository trying to suppress the truth. 😛

Defaming someone in the name of truth is not which is expected from you...

2021-02-28 10:29 UTC, SirusCodes approved these changes

2021-02-28 10:29 UTC, SirusCodes commented on README.md
> +Darshan is G.O.A.T.
This looks perfect.

2021-03-01 05:00 UTC, merged

2021-03-01 06:00 UTC, HarshKapadia2 commented
LMAO 😂

2021-03-01 08:31 UTC, SirusCodes commented
😂😂😂 Power of OS